### ISSUE TITLE
Abrouter\RelatedUsers\Collections\RelatedUsersCollection::append(): Argument #2 ($relatedUserId) must be of type string, null given

### ISSUE THREAD

**Issue by ziming** [abrouter/laravel-abtest#10]
Abrouter\RelatedUsers\Collections\RelatedUsersCollection::append(): Argument #2 ($relatedUserId) must be of type string, null given, called invendor/abrouter/abrouter-php-client/src/Events/Handlers/RelatedUsersStatisticsInterceptor.php on line 45

happen in my production environment

**Comment by ziming** [comment]
after downgrading to 0.19 im still seeing this error in production so i'm commenting out abrouter in my codebase for now.

**Comment by yatsenkolesh** [comment]
Hi. Got it. I'm on fix now

**Comment by yatsenkolesh** [comment]
As I understand it does not affect your users directly, because running on workers.

**Comment by yatsenkolesh** [comment]
@ziming I've fixed it in 0.21.0. Tests are passing + tested in the production of another project
https://github.com/abrouter/laravel-abtest/releases/tag/0.21.0
I'm sorry for the inconvenience
