### ISSUE TITLE
Config options to specify run in which environment

### ISSUE THREAD

**Issue by ziming** [abrouter/laravel-abtest#9]
It will be nice if we can specify which environments to run these code in like

'environments' => [
    'production',
    'staging',
]

This way I don't have to keep doing if checks

**Comment by yatsenkolesh** [comment]
Dear @ziming,

What checks are you doing based on the environment? You don't need to do any checks at all. It's not properly described in the documentation yet, but you can use separate accounts for the different envs. You can just specify the different tokens between environments that belongs to the different accounts. :) 

But your requested feature will be ready by the end of this year.
